In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings("ignore")

In [2]:
#to load csv file
df=pd.read_csv("Admission_Predict.csv")

In [3]:
#to show first five records
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [4]:
#to check nulll values
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [5]:
#cross check
df.dtypes

Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [6]:
#to check data inbalance
df["Research"].value_counts()

1    219
0    181
Name: Research, dtype: int64

In [7]:
#to find duplicated rows
df.duplicated().sum()

0

In [8]:
#select input & output
x=df.drop("Research",axis=1)
y=df["Research"]#1d aaray

In [9]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [10]:
#apply scalling on x_train and x_test
from sklearn.preprocessing import StandardScaler
#create object of StandardScaler class
ss=StandardScaler()
x_train=ss.fit_transform(x_train) #concvert into numpy array 
x_test=ss.transform(x_test)  #also convert into numpoy array 

In [11]:
x_train

array([[-1.34893477, -0.88130652,  0.08218457, ...,  0.05212093,
        -1.53028029, -1.78799905],
       [-0.23389666, -0.35515338, -0.89013991, ..., -0.48839242,
        -0.5688098 , -0.63228765],
       [ 1.64773013, -1.49515186, -1.21424806, ...,  0.05212093,
        -0.5856777 , -0.77675157],
       ...,
       [ 1.76097619,  0.69715292, -0.07986951, ...,  0.05212093,
         0.84809409,  0.81235161],
       [ 0.35846733,  0.78484511,  0.56834681, ...,  0.59263428,
         1.05050893,  1.10127946],
       [-1.36635724, -1.49515186, -0.40397767, ..., -1.56941911,
        -1.36160126, -1.06567942]])

In [12]:
#create a function 
def create_model(model): #user defined function #model=which hold the obj of aklgorithm
    #d1st train the model with 70% data 
    model.fit(x_train,y_train)
    #then test the model with 30% data
    y_pred=model.predict(x_test)
    #generate report
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    return model

In [13]:
from sklearn.metrics import classification_report,confusion_matrix

## LogisticRegression

In [14]:
from sklearn.linear_model import  LogisticRegression

In [15]:
#create obj of from LogisticRegression
lr=LogisticRegression()

In [16]:
#call the function
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        51
           1       0.86      0.78      0.82        69

    accuracy                           0.80       120
   macro avg       0.80      0.80      0.80       120
weighted avg       0.81      0.80      0.80       120

[[42  9]
 [15 54]]


#### recall=0.78

## DecisionTreeClassifier

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
#create obj of from DecisionTreeClassifier by defaut gini index
dt=DecisionTreeClassifier(random_state=1)

In [19]:
#call the model
dt=create_model(dt)

              precision    recall  f1-score   support

           0       0.66      0.80      0.73        51
           1       0.83      0.70      0.76        69

    accuracy                           0.74       120
   macro avg       0.74      0.75      0.74       120
weighted avg       0.76      0.74      0.74       120

[[41 10]
 [21 48]]


#### recall =0.70

## pruning techniques

In [20]:
#Pruning Technique : max_depth  : the value of max_depth cannot more than
#8  (means <=8) 
#create object of DecisionTreeClassifier class with gini index and 
#use parameter max_depth (to remove overfitting)

In [21]:
'''for i in range(1,9):
    dt1=DecisionTreeClassifier(random_state=1,max_depth=i)
    print("max_depth :",i)
    dt1=create_model(dt1)'''

'for i in range(1,9):\n    dt1=DecisionTreeClassifier(random_state=1,max_depth=i)\n    print("max_depth :",i)\n    dt1=create_model(dt1)'

In [22]:
dt1=DecisionTreeClassifier(random_state=1,max_depth=6)
dt1=create_model(dt1)

              precision    recall  f1-score   support

           0       0.75      0.76      0.76        51
           1       0.82      0.81      0.82        69

    accuracy                           0.79       120
   macro avg       0.79      0.79      0.79       120
weighted avg       0.79      0.79      0.79       120

[[39 12]
 [13 56]]


#### recall =0.81

In [23]:
#2nd pruning technique:min_samples_leaf=it is used to reduce overfitting

In [24]:
'''for i in range(45,101):
    dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)
    print("mean_samples_leaf :",i)
    dt2=create_model(dt2)'''

'for i in range(45,101):\n    dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)\n    print("mean_samples_leaf :",i)\n    dt2=create_model(dt2)'

In [25]:
dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=45)
dt2=create_model(dt2)

              precision    recall  f1-score   support

           0       0.64      0.92      0.75        51
           1       0.91      0.61      0.73        69

    accuracy                           0.74       120
   macro avg       0.77      0.77      0.74       120
weighted avg       0.79      0.74      0.74       120

[[47  4]
 [27 42]]


#### recall=0.61

## DecisionTreeClassifier(entropy)

In [26]:
#create obj of from DecisionTreeClassifier by defaut entropy index
dt=DecisionTreeClassifier(random_state=1,criterion="entropy") 

In [27]:
#call the model
dt=create_model(dt)

              precision    recall  f1-score   support

           0       0.57      0.69      0.62        51
           1       0.73      0.62      0.67        69

    accuracy                           0.65       120
   macro avg       0.65      0.65      0.65       120
weighted avg       0.66      0.65      0.65       120

[[35 16]
 [26 43]]


#### recall=0.62

## pruning techniques

In [28]:
#Pruning Technique : max_depth  : the value of max_depth cannot more than
#8  (means <=8) 
#create object of DecisionTreeClassifier class with gini index and 
#use parameter max_depth (to remove overfitting)

In [29]:
'''for i in range(1,9):
    dt1=DecisionTreeClassifier(random_state=1,max_depth=i,criterion="entropy")
    print("max_depth :",i)
    dt1=create_model(dt1)'''

'for i in range(1,9):\n    dt1=DecisionTreeClassifier(random_state=1,max_depth=i,criterion="entropy")\n    print("max_depth :",i)\n    dt1=create_model(dt1)'

In [30]:
dt1=DecisionTreeClassifier(random_state=1,max_depth=4,criterion="entropy")
dt1=create_model(dt1)

              precision    recall  f1-score   support

           0       0.65      0.90      0.75        51
           1       0.90      0.64      0.75        69

    accuracy                           0.75       120
   macro avg       0.77      0.77      0.75       120
weighted avg       0.79      0.75      0.75       120

[[46  5]
 [25 44]]


#### recall=0.62

In [31]:
#2nd pruning technique:min_samples_leaf=it is used to reduce overfitting

In [32]:
'''for i in range(45,101):
    dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=i,criterion="entropy")
    print("mean_samples_leaf :",i)
    dt2=create_model(dt2)'''

'for i in range(45,101):\n    dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=i,criterion="entropy")\n    print("mean_samples_leaf :",i)\n    dt2=create_model(dt2)'

In [33]:
dt2=DecisionTreeClassifier(random_state=1,min_samples_leaf=45,criterion="entropy")
dt2=create_model(dt2)

              precision    recall  f1-score   support

           0       0.64      0.92      0.75        51
           1       0.91      0.61      0.73        69

    accuracy                           0.74       120
   macro avg       0.77      0.77      0.74       120
weighted avg       0.79      0.74      0.74       120

[[47  4]
 [27 42]]


#### recall=0.61

## RandomForestClassifier

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
#create obj of RandomForestClassifier

In [36]:
'''for i in range (10,101):
    rfc=RandomForestClassifier(n_estimators=i,random_state=1)
    print("no of decision trees:",i)
    rfc=create_model(rfc)
    print(rfc)'''

'for i in range (10,101):\n    rfc=RandomForestClassifier(n_estimators=i,random_state=1)\n    print("no of decision trees:",i)\n    rfc=create_model(rfc)\n    print(rfc)'

In [37]:
rfc=RandomForestClassifier(n_estimators=13,random_state=1)
rfc=create_model(rfc)
print(rfc)

              precision    recall  f1-score   support

           0       0.76      0.82      0.79        51
           1       0.86      0.81      0.84        69

    accuracy                           0.82       120
   macro avg       0.81      0.82      0.81       120
weighted avg       0.82      0.82      0.82       120

[[42  9]
 [13 56]]
RandomForestClassifier(n_estimators=13, random_state=1)


#### RECALL=0.81

## pruning technique

In [38]:
#Pruning Technique : max_depth  : the value of max_depth cannot more than
#8  (means <=8) 
#create object of DecisionTreeClassifier class with gini index and 
#use parameter max_depth (to remove overfitting)

In [39]:
'''for i in range(1,9):
    rfc1=RandomForestClassifier(n_estimators=13,random_state=1,max_depth=i)
    print ("no of decision tree:",i)
    rfc1=create_model(rfc1)
    print(rfc1)'''

'for i in range(1,9):\n    rfc1=RandomForestClassifier(n_estimators=13,random_state=1,max_depth=i)\n    print ("no of decision tree:",i)\n    rfc1=create_model(rfc1)\n    print(rfc1)'

In [40]:
rfc1=RandomForestClassifier(n_estimators=13,random_state=1,max_depth=7)
rfc1=create_model(rfc1)
print(rfc1)

              precision    recall  f1-score   support

           0       0.75      0.80      0.77        51
           1       0.85      0.80      0.82        69

    accuracy                           0.80       120
   macro avg       0.80      0.80      0.80       120
weighted avg       0.80      0.80      0.80       120

[[41 10]
 [14 55]]
RandomForestClassifier(max_depth=7, n_estimators=13, random_state=1)


#### RECALL=0.80

In [41]:
#2nd pruning technique:min_samples_leaf=it is used to reduce overfitting

In [42]:
'''for i in range(45,101):
    rfc1=RandomForestClassifier(n_estimators=13,random_state=1,min_samples_leaf=i)
    print ("no of decision tree:",i)
    rfc1=create_model(rfc1)
    print(rfc1)'''

'for i in range(45,101):\n    rfc1=RandomForestClassifier(n_estimators=13,random_state=1,min_samples_leaf=i)\n    print ("no of decision tree:",i)\n    rfc1=create_model(rfc1)\n    print(rfc1)'

In [43]:
rfc1=RandomForestClassifier(n_estimators=13,random_state=1,min_samples_leaf=89)
rfc1=create_model(rfc1)
print(rfc1)

              precision    recall  f1-score   support

           0       0.77      0.71      0.73        51
           1       0.79      0.84      0.82        69

    accuracy                           0.78       120
   macro avg       0.78      0.77      0.78       120
weighted avg       0.78      0.78      0.78       120

[[36 15]
 [11 58]]
RandomForestClassifier(min_samples_leaf=89, n_estimators=13, random_state=1)


#### recall=0.84

##1. AdaBoostClassifier

In [44]:
from sklearn.ensemble import AdaBoostClassifier

In [49]:
'''for i in range(1,14):
    ada = AdaBoostClassifier(n_estimators=i, random_state=1)
    print("No of Decision Stump: ", i)
    ada = create_model(ada)'''

'for i in range(1,14):\n    ada = AdaBoostClassifier(n_estimators=i, random_state=1)\n    print("No of Decision Stump: ", i)\n    ada = create_model(ada)'

In [50]:
ada = AdaBoostClassifier(n_estimators=13, random_state=1)
ada = create_model(ada)
# n_estimators means how many decision stump, decision stump deend on the no of input.....here input =13

              precision    recall  f1-score   support

           0       0.65      0.86      0.74        51
           1       0.87      0.65      0.74        69

    accuracy                           0.74       120
   macro avg       0.76      0.76      0.74       120
weighted avg       0.77      0.74      0.74       120

[[44  7]
 [24 45]]


#### recall : 0.65

## 2. Gradient Boosting(GB) 

In [56]:
from sklearn.ensemble import GradientBoostingClassifier

In [57]:
'''for i in range(10,101):
    gbc = GradientBoostingClassifier(n_estimators=i, random_state=1)  # n_estimators >=10 and <=100
    print("Esimators: ", i)
    gbc = create_model(gbc)'''

'for i in range(10,101):\n    gbc = GradientBoostingClassifier(n_estimators=i, random_state=1)  # n_estimators >=10 and <=100\n    print("Esimators: ", i)\n    gbc = create_model(gbc)'

In [55]:
gbc = GradientBoostingClassifier(n_estimators=64, random_state=1) 
gbc = create_model(gbc)

              precision    recall  f1-score   support

           0       0.71      0.82      0.76        51
           1       0.85      0.75      0.80        69

    accuracy                           0.78       120
   macro avg       0.78      0.79      0.78       120
weighted avg       0.79      0.78      0.78       120

[[42  9]
 [17 52]]


#### recall : 0.75

## 3.Extreame Gradient Boosting

In [59]:
#pip install xgboost

In [60]:
from xgboost import XGBClassifier

In [63]:
'''for i in range(10,100):
    xgc = XGBClassifier(n_estimators= i,reg_alpha =1, random_state =1)
    print('no of estimators:',i)
    xgc = create_model(xgc)'''

"for i in range(10,100):\n    xgc = XGBClassifier(n_estimators= i,reg_alpha =1, random_state =1)\n    print('no of estimators:',i)\n    xgc = create_model(xgc)"

In [64]:
xgc = XGBClassifier(n_estimators= i,reg_alpha =1, random_state =1)
xgc = create_model(xgc)

              precision    recall  f1-score   support

           0       0.66      0.76      0.71        51
           1       0.80      0.71      0.75        69

    accuracy                           0.73       120
   macro avg       0.73      0.74      0.73       120
weighted avg       0.74      0.73      0.73       120

[[39 12]
 [20 49]]


#### recall : 0.71

## svm

In [47]:
from sklearn.svm import LinearSVC

In [65]:
#create obj of linearSVC
svc=LinearSVC(random_state=1)
#no add any error means suppose no outlier in our daataset means it is hard margin

In [66]:
#call function
svc=create_model(svc)

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        51
           1       0.86      0.78      0.82        69

    accuracy                           0.80       120
   macro avg       0.80      0.80      0.80       120
weighted avg       0.81      0.80      0.80       120

[[42  9]
 [15 54]]


#### recall=0.78

In [71]:
#suppose outlier in our dataset means model overfitted 
#so reduce the overfit of model or remove outlier from given dataset ,
#add some external error during training error means soft margin
#Means again create the object of class LinearSVC  and passing parameter
#C means error parameter , the value of C can be <=1
svc1=LinearSVC(random_state=1,C=0.9)  #SOFT MARGIN

In [72]:
#call function
svc1=create_model(svc1)

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        51
           1       0.86      0.78      0.82        69

    accuracy                           0.80       120
   macro avg       0.80      0.80      0.80       120
weighted avg       0.81      0.80      0.80       120

[[42  9]
 [15 54]]


#### recall=0.78

## polynomial kernal function

In [73]:
#call inbuilt class SVC
from sklearn.svm import SVC

In [74]:
#CREATE OBJ of SVC class(use polynomial)
poly_svc=SVC(random_state=1,kernel='poly')

In [75]:
#call function
poly_svc=create_model(poly_svc)

              precision    recall  f1-score   support

           0       0.65      0.59      0.62        51
           1       0.72      0.77      0.74        69

    accuracy                           0.69       120
   macro avg       0.68      0.68      0.68       120
weighted avg       0.69      0.69      0.69       120

[[30 21]
 [16 53]]


#### recall=0.77

## Radial kernal function

In [76]:
#CREATE OBJ of SVC class(use radial) :value of kernal =rbf
#rbf=radial basic function
r_svc=SVC(random_state=1,kernel='rbf')

In [77]:
#call function
r_svc=create_model(r_svc)

              precision    recall  f1-score   support

           0       0.72      0.90      0.80        51
           1       0.91      0.74      0.82        69

    accuracy                           0.81       120
   macro avg       0.81      0.82      0.81       120
weighted avg       0.83      0.81      0.81       120

[[46  5]
 [18 51]]


#### recall-0.74

## highest recall for 1 we got in RandomForestClassifier-84%